config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: %w[chinese italian japanese french belgian]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5, only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def show
    #
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    #
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end


  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    raise
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body class="container mt-3">
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="p-5">
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
  <h4><%= restaurant.name %></h4>
  <p><%= restaurant.address %></p>
  <p>+<%= restaurant.phone_number %></p>
  <p><em><%= restaurant.category %></em></p>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= render "form" %>

<%= link_to "Cancel", restaurant_path,  class: "btn btn-secondary" %>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

  <div class="container d-flex flex-wrap">
    <% @restaurants.each do |restaurant| %>
      <div class="card m-3 p-3" style="width: 14rem;"><%= render restaurant %>
      <%= link_to "details", restaurant_path(restaurant),  class: "btn btn-primary" %></div>
    <% end %>
  </div>

<%= link_to "Add new restaurant", new_restaurant_path, class: "btn btn-warning" %>

app/views/restaurants/new.html.erb
<h1>Create new restaurant</h1>

<%= render "form" %>

<%= link_to "Cancel", restaurants_path %>

app/views/restaurants/show.html.erb
<h1>Restaurant</h1>
<div class="card m-3 p-3" style="width: 20rem;">
  <%= render @restaurant %>
  <p>
    <%= link_to "Edit" , edit_restaurant_path,  class: "btn btn-success" %>
    <%= link_to "Delete", restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
  </p>
  <div>
    <p><%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-warning" %></p>
    <% @restaurant.reviews.each do |review| %>
      <p><%= review.content %></p>
      <p><%= link_to "Delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} , class: "btn btn-danger" %></p>
    <% end %>
  </div>
</div>

<p><%= link_to "Go back to the list" , restaurants_path,  class: "btn btn-primary"%></p>

app/views/reviews/new.html.erb
<h1>Create new review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>